version: '3.5'

services:
  app:
    build: .
    container_name: app
    env_file: database.conf
    ports:
      - 8080:8080  
    expose:
      - 8080
    depends_on:
      - database
    networks: ['mynetwork']


  database:
    image: postgres:latest
    container_name: database
    env_file: database.conf
    ports:
      - 5432:5432  
    volumes:
       - db_volume:/var/lib/postgresql/data

volumes:
  db_volume:
